=== jborghino/Mandataire/src/main/resources/model.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">


	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="1" name="concessionnaire" type="concessionnaire" />
				<xs:element maxOccurs="unbounded" name="vehicule" type="vehicule" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>




	<xs:complexType name="concessionnaire">
		<xs:sequence>
			<xs:element name="siren" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="vehicule">
		<xs:sequence>
			<xs:element name="marque" type="xs:string" />
			<xs:element name="modele" type="xs:string" />
			<xs:element name="couleur" type="xs:string" />
			<xs:element name="nb_portes" type="xs:int" />
			<xs:element name="nb_places" type="xs:int" />
			<xs:element name="equipement" type="xs:string" />
			<xs:element name="motorisation" type="xs:string" />
			<xs:element name="emission" type="xs:int" />
			<xs:element name="url" type="xs:string" />
			<xs:element name="prix" type="xs:int" />
		</xs:sequence>
	</xs:complexType>

	<!-- <xs:element name="client"> -->
	<!-- <xs:complexType> -->
	<!-- <xs:sequence> -->
	<!-- <xs:element name="nom" type="xs:string" /> -->
	<!-- <xs:element name="prenom" type="xs:string" /> -->
	<!-- <xs:element name="adresse" type="xs:string" /> -->
	<!-- <xs:element name="mail" type="xs:string" /> -->
	<!-- </xs:sequence> -->
	<!-- </xs:complexType> -->
	<!-- </xs:element> -->

</xs:schema>

=== jborghino/Mandataire/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model.xsd">
  <concessionnaire>
    <siren>siren</siren>
  </concessionnaire>
  <vehicule>
    <marque>marque</marque>
    <modele>modele</modele>
    <couleur>couleur</couleur>
    <nb_portes>0</nb_portes>
    <nb_places>0</nb_places>
    <equipement>equipement</equipement>
    <motorisation>motorisation</motorisation>
    <emission>0</emission>
    <url>url</url>
    <prix>0</prix>
  </vehicule>
   <vehicule>
    <marque>marque1</marque>
    <modele>modele1</modele>
    <couleur>couleur1</couleur>
    <nb_portes>01</nb_portes>
    <nb_places>01</nb_places>
    <equipement>equipement1</equipement>
    <motorisation>motorisation1</motorisation>
    <emission>01</emission>
    <url>url1</url>
    <prix>01</prix>
  </vehicule>
</root>

=== jborghino/Mandataire/mandataire_26-05-14.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model.xsd">
  <concessionnaire>
    <siren>siren</siren>
  </concessionnaire>
  <vehicule>
    <marque>peugot</marque>
    <modele>206</modele>
    <couleur>noir</couleur>
    <nb_portes>3</nb_portes>
    <nb_places>5</nb_places>
    <equipement></equipement>
    <motorisation></motorisation>
    <emission>0</emission>
    <url>http://www.car-luxury-agency.com/blog/wp-content/uploads/2012/03/Audi-R8-Spyder-100x100.jpg</url>
    <prix>4000</prix>
  </vehicule>
</root>
